import uuid
from django.db import migrations, models
import django.db.models.deletion
import apps.medical_records.models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [('medical_records','0001_initial'), ('appointments','0001_initial'), ('users','0001_initial')]
    operations = [
        migrations.CreateModel(name='Consultation', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('diagnosis', models.TextField()), ('clinical_notes', models.TextField(blank=True, null=True)), ('date', models.DateField(default=django.utils.timezone.localdate)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('appointment', models.OneToOneField(db_column='appointment_id', on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='appointments.appointment')), ('medical_record', models.ForeignKey(db_column='medical_record_id', on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='medical_records.medicalrecord')), ('vet', models.ForeignKey(db_column='vet_id', on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='users.veterinarian'))], options={'db_table':'consultations','ordering':['-date','-created_at']}),
        migrations.CreateModel(name='Treatment', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('name', models.CharField(max_length=200)), ('description', models.TextField(blank=True, null=True)), ('start_date', models.DateField(blank=True, null=True)), ('duration_days', models.IntegerField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='medical_records.consultation'))], options={'db_table':'treatments'}),
        migrations.CreateModel(name='Prescription', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('medicine_name', models.CharField(max_length=200)), ('dosage', models.CharField(max_length=200)), ('frequency', models.CharField(blank=True, max_length=200, null=True)), ('duration_days', models.IntegerField(blank=True, null=True)), ('supply_id', models.UUIDField(blank=True, null=True)), ('instructions', models.TextField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.consultation'))], options={'db_table':'prescriptions'}),
        migrations.CreateModel(name='MedicalAttachment', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('file', models.FileField(upload_to=apps.medical_records.models.attachment_upload_path)), ('attachment_type', models.CharField(choices=[('XRAY','Radiografía'),('LAB','Laboratorio'),('OTHER','Otro')], max_length=10)), ('description', models.CharField(blank=True, max_length=255, null=True)), ('uploaded_at', models.DateTimeField(auto_now_add=True)), ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='medical_records.consultation'))], options={'db_table':'medical_attachments'}),
        migrations.CreateModel(name='SupplyUsed', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('supply_id', models.UUIDField()), ('supply_name', models.CharField(blank=True, max_length=200, null=True)), ('quantity', models.DecimalField(decimal_places=2, max_digits=10)), ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ('sync_status', models.CharField(choices=[('SYNCED','Sincronizado'),('PENDING_SYNC','Pendiente de sincronización'),('FAILED','Fallido')], default='PENDING_SYNC', max_length=20)), ('created_at', models.DateTimeField(auto_now_add=True)), ('consultation', models.ForeignKey(db_column='consultation_id', on_delete=django.db.models.deletion.CASCADE, related_name='supplies_used', to='medical_records.consultation'))], options={'db_table':'supply_used'}),
    ]
