# Generated by Django 5.2.14 on 2026-05-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del insumo')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Existencias físicas reales disponibles')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('min_stock_alert', models.IntegerField(default=0, verbose_name='Umbral mínimo de almacén para disparar alertas')),
            ],
        ),
    ]
