# Generated by Django 5.2.14 on 2026-05-21 03:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('id_supply', models.AutoField(primary_key=True, serialize=False)),
                ('supply_name', models.CharField(max_length=150, unique=True, verbose_name='Nombre comercial del insumo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción o detalles técnicos')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo unitario base de referencia en USD')),
                ('minimum_stock', models.PositiveIntegerField(verbose_name='Umbral mínimo de seguridad')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='Existencias globales reales acumuladas')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id_purchase_request', models.AutoField(primary_key=True, serialize=False)),
                ('request_status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Aprobada por Gerencia'), ('REJECTED', 'Rechazada por Gerencia')], default='PENDING', max_length=15, verbose_name='Estado actual del workflow')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación de la solicitud')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se aprobó/rechazó')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Justificación obligatoria en caso de rechazo')),
                ('id_applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Veterinario solicitante')),
                ('id_approver_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Gerente que resolvió la orden')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequestDetail',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Cantidad solicitada (mínimo 1)')),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo congelado al momento del pedido')),
                ('id_purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='stock.purchaserequest', verbose_name='Solicitud cabecera')),
                ('id_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.medicalsupply', verbose_name='Insumo médico requerido')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyBatch',
            fields=[
                ('id_batch', models.AutoField(primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=50, unique=True, verbose_name='Código único de lote provisto por laboratorio')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Cantidad inicial ingresada')),
                ('quantity_available', models.PositiveIntegerField(verbose_name='Unidades remanentes reales no consumidas')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de registro del ingreso')),
                ('expiration_date', models.DateField(verbose_name='Fecha de caducidad estipulada por fabricante')),
                ('id_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.medicalsupply', verbose_name='Insumo médico de referencia')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlertLog',
            fields=[
                ('id_alert', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('MINIMUM_STOCK', 'Stock por debajo del mínimo'), ('NEAR_EXPIRATION', 'Lote cercano a vencer o caducado')], max_length=25, verbose_name='Naturaleza de la desviación')),
                ('notification_detail', models.TextField(verbose_name='Texto redactado con el detalle del evento')),
                ('alert_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de generación de la alerta')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Flag de subsanado')),
                ('id_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.medicalsupply', verbose_name='Insumo afectado')),
                ('id_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.supplybatch', verbose_name='Lote afectado (opcional)')),
            ],
        ),
    ]
