# Generated by Django 6.0.4 on 2026-05-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_purchaseorder_manager_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='min_stock_alert',
            new_name='min_stock',
        ),
    ]
