# Generated by Django 6.0.4 on 2026-05-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_min_stock_alert_supply_min_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_unit', models.CharField(max_length=20)),
            ],
        ),
    ]
