import uuid
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('pets','0001_initial'), ('users','0001_initial')]
    operations = [
        migrations.CreateModel(name='VaccinationPlan', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('is_active', models.BooleanField(default=True)), ('notes', models.TextField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_plans', to='users.veterinarian')), ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_plans', to='pets.pet'))], options={'db_table':'vaccination_plans'}),
        migrations.CreateModel(name='VaccinationPlanItem', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('vaccine_name', models.CharField(max_length=200)), ('scheduled_date', models.DateField()), ('supply_id', models.UUIDField(blank=True, null=True)), ('notes', models.TextField(blank=True, null=True)), ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vaccinations.vaccinationplan'))], options={'db_table':'vaccination_plan_items','ordering':['scheduled_date']}),
        migrations.CreateModel(name='VaccinationEvent', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('vaccine_name', models.CharField(max_length=200)), ('applied_date', models.DateField()), ('batch_number', models.CharField(max_length=100)), ('dose', models.CharField(blank=True, max_length=100, null=True)), ('next_due_date', models.DateField(blank=True, null=True)), ('supply_id', models.UUIDField(blank=True, null=True)), ('quantity_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_events', to='users.veterinarian')), ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_events', to='pets.pet')), ('plan_item', models.ForeignKey(blank=True, db_column='plan_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='vaccinations.vaccinationplanitem'))], options={'db_table':'vaccination_events','ordering':['-applied_date']}),
    ]
