# Generated by Django 6.0.5 on 2026-05-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_role_permissions_remove_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='clinical_staff',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
