# Generated by Django 6.0.4 on 2026-05-27 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_receptionist_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalstaff',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clinicalstaff',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='clinicalstaff',
            name='hired_at',
        ),
        migrations.RemoveField(
            model_name='clinicalstaff',
            name='phone',
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='natural_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clinicalstaff',
            name='natural_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.naturalperson'),
        ),
    ]
