# Generated by Django 5.2.14 on 2026-05-28 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_notes', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
