# Generated by Django 6.0.4 on 2026-05-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_remove_owner_phone_number_owner_dni_and_more'),
        ('users', '0004_remove_clinicalstaff_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='owner',
            name='natural_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.naturalperson'),
        ),
    ]
